version: '3'
services:
  symbols_db:
    build:
      dockerfile: Dockerfile.dev
      context: ./symbol-service/migrations
    volumes:
      - ./symbol-service/migrations/data:/var/lib/postgresql/data
  symbols_service:
    build:
      dockerfile: Dockerfile.dev
      context: ./symbol-service
    volumes:
      - ./symbol-service:/go/src/microservices-project/symbol-service
      - /go/src/microservices-project/symbol-service/vendor
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_USER=symbols_dev
      - POSTGRES_PASSWORD=development
      - POSTGRES_DB=symbols_dev
      - POSTGRES_HOST=symbols_db
  quotes_db:
    build:
      dockerfile: Dockerfile.dev
      context: ./quote-service/migrations
    volumes:
      - ./quote-service/migrations/data:/var/lib/postgresql/data
  quote_service:
    tty: true
    build:
      dockerfile: Dockerfile.dev
      context: ./quote-service
    volumes:
      - ./quote-service:/go/src/microservices-project/quote-service
      - /go/src/microservices-project/quote-service/vendor
    ports:
      - "3000:3000"
    environment:
      - ALPHA_VANTAGE_KEY
      - SYMBOL_SERVICE_HOST=symbols_service
      - SYMBOL_SERVICE_PORT=5000
      - POSTGRES_USER=quotes_dev
      - POSTGRES_PASSWORD=development
      - POSTGRES_DB=quotes_dev
      - POSTGRES_HOST=quotes_db
