version: '3'
services:
  symbols_db:
    build:
      dockerfile: Dockerfile.dev
      context: ./symbol-service/migrations
    volumes:
      - ./symbol-service/migrations/data:/var/lib/postgresql/data
  symbols_service:
    build:
      dockerfile: Dockerfile.dev
      context: ./symbol-service
    volumes:
      - /go/src/microservices-project/symbol-service/vendor
      - ./symbol-service:/go/src/microservices-project/symbol-service/
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_USER=symbols_dev
      - POSTGRES_PASSWORD=development
      - POSTGRES_DB=symbols_dev
      - POSTGRES_HOST=symbols_db
  timeseries_worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./timeseries-worker
    tty: true
    environment:
      - ALPHA_VANTAGE_KEY
