FROM golang:1.12.5-alpine3.9

# INSTALL OS DEPENDENCIES
RUN apk update && apk add --no-cache git
RUN apk add --no-cache curl
# TODO(adeaver): make this install a specific version
RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

WORKDIR $GOPATH/src/microservices-project/symbol-service

# INSTALL GOLANG DEPENDENCIES
COPY Gopkg.lock .
COPY Gopkg.toml .
RUN dep ensure -vendor-only

RUN go get github.com/codegangsta/gin

COPY . .

CMD ["gin", "-p", "5000", "-a", "5050", "run", "main.go"]
